#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
# DEFAULT='#8b0000aa'
DEFAULT='#ffffffff'
WRONG='#ff3131ff'

# '#00ff00ff'

i3lock \
--insidever-color=$BLANK     \
--ringver-color=$BLANK	 \
\
--insidewrong-color=$BLANK   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$DEFAULT       \
--wrong-color=$WRONG         \
--time-color=$DEFAULT        \
--date-color=$DEFAULT        \
--layout-color=$DEFAULT      \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 9                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"    \
--keylayout 1                \
