#!/bin/sh

pkill picom  # Kill picom before locking
i3lock -c 000000 &  # Run i3lock in the background

# Wait until i3lock exits
while pgrep -x i3lock >/dev/null; do
    sleep 1
done

picom --experimental-backends &  # Restart picom after unlocking